// ============================================================================
//  anvil_1ipc_sva.sv
//
//  Static-contract assertions for the 1-IPC Anvil MIPS pipeline
//  (anvil_code_pipelined/mips_anvil_pipelined.sv, generated by anvilc from
//   types/fetch/decode/execute/memory/writeback/top.anv).
//
//  WHY THIS FILE EXISTS
//  --------------------
//  Under `@#1 - @#1` the compiler emits NO req_valid / req_ack / res_valid /
//  res_ack wires: 0 in this RTL, against 464 in the serialised version.  The
//  handshake was a RUN-TIME negotiation ("are you ready?" / "yes").  A static
//  contract is a COMPILE-TIME promise: "I produce and consume exactly one
//  message on this channel every cycle, on every path, forever."  Nothing in
//  the generated hardware checks that promise.  If a stage ever misses a beat
//  there is no ack to stall on and the pipeline silently reads garbage.
//
//  These assertions are the run-time check that the removed ack wires used to
//  be.  Groups A and B are the core of it; everything after that is the
//  hazard/forwarding suite, which for the first time in this project has
//  satisfiable antecedents (the serialised design ran one instruction at a
//  time, so P1/P2/P3 passed vacuously there).
//
//    A  cadence     - the contract's own hardware embodiment: every process's
//                     event token fires every cycle, unconditionally
//    B  pairing     - one message produced and one consumed per channel per
//                     cycle: each consumer's input register equals $past(bus)
//    C  fan-out     - one logical message carried on two physical buses must
//                     stay bit-identical (a bug class the ack never covered
//                     either, and that only exists because the ack is gone)
//    D  stall       - the payload-not-cadence trick, formalised
//    E  flush       - branch squash has no architectural side effect
//    F  datapath    - forwarding priority, $zero gating, EX/MEM-from-load
//    G  architecture- $zero immutability, register-file commit
//    H  covers      - the vacuity instrument.  An unhit cover is the only
//                     evidence that separates "holds" from "never tested".
//
//  ---------------------------------------------------------------------------
//  MEASURED - Verilator 5.020, this file as delivered, tb_mips_pipelined.sv,
//             40 cycles.  Reproduce with the commands under RUN below.
//  ---------------------------------------------------------------------------
//  Baseline .......... 32 assertions, 12 covers, 0 violations.
//  Harness liveness .. a deliberately false probe fires, so a clean run is a
//                      real pass and not a dead harness.
//  Cover hits ........ stall 1 | flush 1 | fwdA EX/MEM 4 | fwdA MEM/WB 2 |
//                      priority conflict 1 | commit 4 | store 1 |
//                      FIVE STAGES OCCUPIED 27 of 40 cycles |
//                      fwdB EX/MEM 0 <- UNHIT | fwdB MEM/WB 0 <- UNHIT |
//                      $zero-forward candidate 0 <- UNHIT
//                      The three unhit covers are a STIMULUS hole, not a
//                      property defect - the same operand-B hole the port
//                      review found in the serialised suite.  F2 is therefore
//                      VACUOUS on this program.  Close it by appending the
//                      five instructions from the review (operand-B forwards
//                      one-back and two-back) plus `add $zero, r1, r1`
//                      followed by a reader of $zero, and running 32+ cycles.
//
//  Mutation results - one edit to the generated RTL, predictions written
//  before execution:
//    M-A  load-use interlock deleted (hz forced to 0) AND D5 disabled, i.e.
//         the hazard unit removed and the assertion "fixed" to match
//         -> killed by F3 ALONE.  End state wrong: r2 = -20, dmem = 0.
//    M-B  Decode's loop-back divided by two, i.e. a loop body two cycles wide
//         instead of one - exactly what one stray `>>` produces
//         -> killed by A1 (19x), A2 (19x), B4 (18x), D4, G2.
//    M-C  Writeback's two fan-out copies made to differ by one bit
//         -> killed by C1 ALONE (40x).  End state catastrophically wrong
//            (r3 = 20; r3 is the register the branch shadow must never write).
//    M-D  the `fw_rd != 5'd0` guard on EX/MEM forwarding dropped
//         -> SURVIVED, invisible end-to-end AND to this suite, because F2's
//            antecedent needs an instruction that writes a non-zero result to
//            $zero and this program has none.  Reported, not hidden: the
//            honest score is 3 killed, 1 survived, and the survivor is a
//            stimulus hole with a known fix.
//
//  BIND COMPLETENESS
//  -----------------
//  The checker declares 55 input ports and the bind at the bottom connects all
//  55.  A `bind` is an ordinary module instantiation: an unlisted input is
//  UNDRIVEN, which is 'x in 4-state simulation (antecedent never matches ->
//  vacuous pass) and a stable 0 in 2-state Verilator (unconditional property
//  evaluates against a constant -> FALSE pass).  Property A0 below is the
//  harness's self-check: every input must be known once reset is released.
//  Do not add a port without adding it to the bind.
//
//  RUN
//  ---
//    $ verilator --binary --assert --timing -Wno-fatal --top-module tb \
//        mips_anvil_pipelined.sv anvil_1ipc_sva.sv tb_mips_pipelined.sv
//    $ obj_dir/Vtb
//
//    $ xvlog -sv mips_anvil_pipelined.sv anvil_1ipc_sva.sv tb_mips_pipelined.sv
//    $ xelab -R tb
//
//  The simulator stops on the first failure.  To enumerate every firing property
//  in one run - which is how the mutation table above was produced - make a
//  soft copy first:
//
//    $ sed 's/else \$error(/else \$display("VIOLATION: ",/' \
//          anvil_1ipc_sva.sv > anvil_1ipc_sva_soft.sv
//
//  Icarus 12 does not implement concurrent assertions; use Verilator or xsim.
// ============================================================================

`ifndef ANVIL_1IPC_SVA_SV
`define ANVIL_1IPC_SVA_SV

// ----------------------------------------------------------------------------
//  Channel payload layouts.
//
//  Anvil packs a struct with the FIRST-declared field at the MSB and the
//  LAST-declared field at bit 0.  Verified field by field against the slices
//  the compiler emitted, e.g. in module Execute:
//      assign thread_0_wire$75 = _ep_in_req_0[120 +: 32];   // id_ex.rd1
//      assign thread_0_wire$89 = _ep_in_req_0[  1 +:  1];   // id_ex.branch_zero
//  If types.anv changes, these offsets change.  Re-derive them from the
//  generated file, not from the struct declaration alone.
// ----------------------------------------------------------------------------

// if_id_t : 65 bits  { pc:32, instr:32, valid:1 }
`define IFID_PC(b)        (b[33 +: 32])
`define IFID_INSTR(b)     (b[ 1 +: 32])
`define IFID_VALID(b)     (b[ 0 +:  1])

// id_ex_t : 152 bits { rd1,rd2,imm,addr21 :32 | rs,rt,rd :5 | 9 control bits }
`define IDEX_RD1(b)       (b[120 +: 32])
`define IDEX_RD2(b)       (b[ 88 +: 32])
`define IDEX_IMM(b)       (b[ 56 +: 32])
`define IDEX_ADDR21(b)    (b[ 24 +: 32])
`define IDEX_RS(b)        (b[ 19 +:  5])
`define IDEX_RT(b)        (b[ 14 +:  5])
`define IDEX_RD(b)        (b[  9 +:  5])
`define IDEX_ALU_SUB(b)   (b[  8 +:  1])
`define IDEX_ALU_SRC(b)   (b[  7 +:  1])
`define IDEX_REG_DST(b)   (b[  6 +:  1])
`define IDEX_MEM_READ(b)  (b[  5 +:  1])
`define IDEX_MEM_WRITE(b) (b[  4 +:  1])
`define IDEX_REG_WRITE(b) (b[  3 +:  1])
`define IDEX_MEM_TO_REG(b)(b[  2 +:  1])
`define IDEX_BRANCH_Z(b)  (b[  1 +:  1])
`define IDEX_VALID(b)     (b[  0 +:  1])

// ex_mem_t : 73 bits { alu_result:32, write_data:32, dest_reg:5, 4 control }
`define EXMEM_ALU(b)      (b[ 41 +: 32])
`define EXMEM_WDATA(b)    (b[  9 +: 32])
`define EXMEM_DEST(b)     (b[  4 +:  5])
`define EXMEM_MEM_READ(b) (b[  3 +:  1])
`define EXMEM_MEM_WR(b)   (b[  2 +:  1])
`define EXMEM_REG_WR(b)   (b[  1 +:  1])
`define EXMEM_M2R(b)      (b[  0 +:  1])

// mem_wb_t : 71 bits { alu_result:32, mem_data:32, dest_reg:5, 2 control }
`define MEMWB_ALU(b)      (b[ 39 +: 32])
`define MEMWB_MDATA(b)    (b[  7 +: 32])
`define MEMWB_DEST(b)     (b[  2 +:  5])
`define MEMWB_REG_WR(b)   (b[  1 +:  1])
`define MEMWB_M2R(b)      (b[  0 +:  1])

// wb_update_t : 38 bits { write_data:32, dest_reg:5, reg_write:1 }
`define WB_DATA(b)        (b[  6 +: 32])
`define WB_DEST(b)        (b[  1 +:  5])
`define WB_WE(b)          (b[  0 +:  1])

// branch_update_t : 33 bits { branch_taken:1, branch_target:32 }
`define BR_TAKEN(b)       (b[ 32 +:  1])
`define BR_TGT(b)         (b[  0 +: 32])


module anvil_1ipc_sva (
  // ---- clock / reset ------------------------------------------------- 2 ---
  input logic         clk_i,
  input logic         rst_ni,

  // ---- the nine statically-scheduled channel buses ------------------- 9 ---
  input logic [ 64:0] if_id,        // Fetch     -> Decode
  input logic [151:0] id_ex,        // Decode    -> Execute
  input logic [ 72:0] ex_mem,       // Execute   -> Memory
  input logic [ 70:0] mem_wb,       // Memory    -> Writeback
  input logic [ 37:0] wb_id,        // Writeback -> Decode   (commit + bypass)
  input logic [ 37:0] wb_ex,        // Writeback -> Execute  (MEM/WB forward)
  input logic [ 32:0] br_if,        // Execute   -> Fetch    (redirect)
  input logic [ 32:0] br_id,        // Execute   -> Decode   (flush)
  input logic         stall,        // Decode    -> Fetch    (load-use)

  // ---- cadence: each process's event-0 token ------------------------- 5 ---
  input logic         ev_fetch,
  input logic         ev_decode,
  input logic         ev_execute,
  input logic         ev_memory,
  input logic         ev_writeback,

  // ---- Fetch state ---------------------------------------------------- 2 ---
  input logic [ 31:0] f_pc,
  input logic         f_booted,

  // ---- Decode state --------------------------------------------------- 6 ---
  input logic [ 31:0] d_ifid_pc,
  input logic [ 31:0] d_ifid_instr,
  input logic         d_ifid_valid,
  input logic [1023:0] d_regs,
  input logic         d_sh_mem_read,
  input logic [  4:0] d_sh_rt,

  // ---- Execute state (ID/EX register + EX/MEM forwarding shadow) ----- 18 ---
  input logic [ 31:0] x_rd1,
  input logic [ 31:0] x_rd2,
  input logic [ 31:0] x_imm,
  input logic [ 31:0] x_addr21,
  input logic [  4:0] x_rs,
  input logic [  4:0] x_rt,
  input logic [  4:0] x_rd,
  input logic         x_alu_sub,
  input logic         x_alu_src,
  input logic         x_reg_dst,
  input logic         x_mem_read,
  input logic         x_mem_write,
  input logic         x_reg_write,
  input logic         x_mem_to_reg,
  input logic         x_branch_zero,
  input logic [  4:0] x_fw_rd,
  input logic [ 31:0] x_fw_data,
  input logic         x_fw_we,

  // ---- Memory state (EX/MEM register + dmem) ------------------------- 8 ---
  input logic [ 31:0] m_alu,
  input logic [ 31:0] m_wdata,
  input logic [  4:0] m_dest,
  input logic         m_mem_write,
  input logic         m_reg_write,
  input logic         m_mem_to_reg,
  input logic [8191:0] m_dmem,
  input logic         m_booted,

  // ---- Writeback state (MEM/WB register) ----------------------------- 5 ---
  input logic [ 31:0] w_alu,
  input logic [ 31:0] w_mdata,
  input logic [  4:0] w_dest,
  input logic         w_reg_write,
  input logic         w_mem_to_reg
);
  // ======================= 55 ports.  All 55 are bound. ===================

  // --------------------------------------------------------------------------
  //  History guard.  $past is meaningless in the first cycle out of reset.
  // --------------------------------------------------------------------------
  logic [1:0] rst_hist;
  always_ff @(posedge clk_i or negedge rst_ni)
    if (!rst_ni) rst_hist <= 2'b00;
    else         rst_hist <= {rst_hist[0], 1'b1};
  wire past_ok = rst_hist[1];

  // --------------------------------------------------------------------------
  //  Register-file accessor.  regs_q is one flat 1024-bit vector; register i
  //  occupies regs_q[i*32 +: 32].
  // --------------------------------------------------------------------------
  function automatic logic [31:0] rf (input logic [4:0] i);
    rf = d_regs[{i, 5'd0} +: 32];
  endfunction

  function automatic logic [31:0] dmem_w (input logic [7:0] i);
    dmem_w = m_dmem[{i, 5'd0} +: 32];
  endfunction

  // ==========================================================================
  //  A.  CADENCE - the contract's own hardware embodiment
  //
  //  `@#1 - @#1` on every channel forces every loop body to be exactly one
  //  cycle wide.  The compiler realises that as a two-event ring per process:
  //
  //      assign EVENTS0[1].event_current = _thread_0_event_counter_1_1_q;
  //      assign _thread_0_event_counter_1_1_n = EVENTS0[0].event_current;
  //      assign EVENTS0[0].event_current = _init_0 || EVENTS0[1].event_current;
  //
  //  which is a free-running token: EVENTS0[0] is high in EVERY cycle after
  //  reset.  There is no state in which a process is "waiting", which is the
  //  structural reason deadlock is unreachable here.  If a future edit puts a
  //  second `>>`-separated step back into any loop body, the body stops being
  //  one cycle wide, the token no longer fires every cycle, and A1 fires.
  //  A1 is therefore the single most important property in this file: it is
  //  the only thing anywhere in the design that checks the promise the static
  //  contract makes.  The 218-event FSM of the serialised design became 10
  //  events in total.  (Demonstrated: mutation M-B.)
  // ==========================================================================

  a_A0_ports_driven: assert property (@(posedge clk_i) disable iff (!rst_ni)
    past_ok |-> !$isunknown({if_id, id_ex, ex_mem, mem_wb, wb_id, wb_ex,
                             br_if, br_id, stall,
                             ev_fetch, ev_decode, ev_execute, ev_memory,
                             ev_writeback, f_pc, f_booted, d_ifid_pc,
                             d_ifid_instr, d_ifid_valid, d_sh_mem_read, d_sh_rt,
                             x_rs, x_rt, x_rd, x_fw_rd, x_fw_we,
                             m_dest, m_reg_write, w_dest, w_reg_write}))
    else $error("A0: a bound port is X - the harness itself is broken");

  a_A1_cadence_fetch:     assert property (@(posedge clk_i) disable iff (!rst_ni)
    ev_fetch     === 1'b1) else $error("A1: Fetch missed a beat - @#1 violated");
  a_A1_cadence_decode:    assert property (@(posedge clk_i) disable iff (!rst_ni)
    ev_decode    === 1'b1) else $error("A1: Decode missed a beat - @#1 violated");
  a_A1_cadence_execute:   assert property (@(posedge clk_i) disable iff (!rst_ni)
    ev_execute   === 1'b1) else $error("A1: Execute missed a beat - @#1 violated");
  a_A1_cadence_memory:    assert property (@(posedge clk_i) disable iff (!rst_ni)
    ev_memory    === 1'b1) else $error("A1: Memory missed a beat - @#1 violated");
  a_A1_cadence_writeback: assert property (@(posedge clk_i) disable iff (!rst_ni)
    ev_writeback === 1'b1) else $error("A1: Writeback missed a beat - @#1 violated");

  // A2 - the cadence is global, not per-process: all five fire together, every
  //      cycle.  A design in which four stages run and one does not is exactly
  //      the silent-garbage failure the ack used to prevent.
  a_A2_cadence_lockstep: assert property (@(posedge clk_i) disable iff (!rst_ni)
    (ev_fetch === ev_decode) && (ev_decode === ev_execute) &&
    (ev_execute === ev_memory) && (ev_memory === ev_writeback))
    else $error("A2: processes are not in lockstep - the static schedule has slipped");

  // ==========================================================================
  //  B.  PAIRING - one message produced, one consumed, per channel per cycle
  //
  //  With no ack there is nothing in the hardware that says "I took it".  The
  //  observable form of "the consumer took exactly the message the producer
  //  drove" is that the consumer's input latch, one cycle later, holds the
  //  bus value from this cycle.  Each stage owns exactly one pipeline register
  //  (its own input latch), so this is checkable field by field.
  //
  //  These five properties ARE the deleted ack wires, re-expressed as an
  //  obligation on state rather than on a protocol.
  // ==========================================================================

  // B1 - Execute consumes id_ex.  Unconditional: Execute never holds.
  a_B1_execute_consumes_id_ex: assert property (@(posedge clk_i) disable iff (!rst_ni)
    past_ok |-> (x_rd1         === $past(`IDEX_RD1(id_ex))       &&
                 x_rd2         === $past(`IDEX_RD2(id_ex))       &&
                 x_imm         === $past(`IDEX_IMM(id_ex))       &&
                 x_addr21      === $past(`IDEX_ADDR21(id_ex))    &&
                 x_rs          === $past(`IDEX_RS(id_ex))        &&
                 x_rt          === $past(`IDEX_RT(id_ex))        &&
                 x_rd          === $past(`IDEX_RD(id_ex))        &&
                 x_alu_sub     === $past(`IDEX_ALU_SUB(id_ex))   &&
                 x_alu_src     === $past(`IDEX_ALU_SRC(id_ex))   &&
                 x_reg_dst     === $past(`IDEX_REG_DST(id_ex))   &&
                 x_mem_read    === $past(`IDEX_MEM_READ(id_ex))  &&
                 x_mem_write   === $past(`IDEX_MEM_WRITE(id_ex)) &&
                 x_reg_write   === $past(`IDEX_REG_WRITE(id_ex)) &&
                 x_mem_to_reg  === $past(`IDEX_MEM_TO_REG(id_ex))&&
                 x_branch_zero === $past(`IDEX_BRANCH_Z(id_ex))))
    else $error("B1: Execute did not latch the id_ex message driven last cycle");

  // B2 - Memory consumes ex_mem.
  a_B2_memory_consumes_ex_mem: assert property (@(posedge clk_i) disable iff (!rst_ni)
    past_ok |-> (m_alu        === $past(`EXMEM_ALU(ex_mem))   &&
                 m_wdata      === $past(`EXMEM_WDATA(ex_mem)) &&
                 m_dest       === $past(`EXMEM_DEST(ex_mem))  &&
                 m_mem_write  === $past(`EXMEM_MEM_WR(ex_mem))&&
                 m_reg_write  === $past(`EXMEM_REG_WR(ex_mem))&&
                 m_mem_to_reg === $past(`EXMEM_M2R(ex_mem))))
    else $error("B2: Memory did not latch the ex_mem message driven last cycle");

  // B3 - Writeback consumes mem_wb.
  a_B3_writeback_consumes_mem_wb: assert property (@(posedge clk_i) disable iff (!rst_ni)
    past_ok |-> (w_alu        === $past(`MEMWB_ALU(mem_wb))    &&
                 w_mdata      === $past(`MEMWB_MDATA(mem_wb))  &&
                 w_dest       === $past(`MEMWB_DEST(mem_wb))   &&
                 w_reg_write  === $past(`MEMWB_REG_WR(mem_wb)) &&
                 w_mem_to_reg === $past(`MEMWB_M2R(mem_wb))))
    else $error("B3: Writeback did not latch the mem_wb message driven last cycle");

  // B4 - Decode consumes if_id, with the two documented exceptions.  This is
  //      the ONLY consumer in the design that is allowed not to advance, and
  //      the exception is exactly the stall trick.  Priority in decode.anv is
  //      hz first, then flush, so the nesting order below is load-bearing.
  a_B4_decode_consumes_if_id: assert property (@(posedge clk_i) disable iff (!rst_ni)
    past_ok |-> (d_ifid_instr === ($past(stall)          ? $past(d_ifid_instr)
                                 : $past(`BR_TAKEN(br_id)) ? 32'd0
                                 : $past(`IFID_INSTR(if_id)))   &&
                 d_ifid_valid === ($past(stall)          ? $past(d_ifid_valid)
                                 : $past(`BR_TAKEN(br_id)) ? 1'b0
                                 : $past(`IFID_VALID(if_id)))   &&
                 d_ifid_pc    === ($past(stall)          ? $past(d_ifid_pc)
                                 : $past(`IFID_PC(if_id)))))
    else $error("B4: Decode's IF/ID latch does not match if_id / stall / flush");

  // B5 - Fetch's PC follows the documented four-way priority, every cycle:
  //      boot hold > branch redirect > load-use hold > pc+4.
  a_B5_fetch_next_pc: assert property (@(posedge clk_i) disable iff (!rst_ni)
    past_ok |-> f_pc === (!$past(f_booted)           ? $past(f_pc)
                        : $past(`BR_TAKEN(br_if))    ? $past(`BR_TGT(br_if))
                        : $past(stall)               ? $past(f_pc)
                                                     : $past(f_pc) + 32'd4))
    else $error("B5: PC does not follow the boot/branch/stall/+4 priority");

  // ==========================================================================
  //  C.  FAN-OUT - a bug class that only exists because the ack is gone
  //
  //  Writeback sends one logical wb_update on two physical channels (wb_id,
  //  wb_ex); Execute sends one logical branch_update on two (br_if, br_id).
  //  Under a dynamic contract these were still two transactions, but each one
  //  was acknowledged.  Under a static contract they are two bare buses with
  //  nothing tying them together.  If they ever diverge, Decode and Execute
  //  disagree about the committed value, or Fetch and Decode disagree about
  //  whether a branch was taken - and nothing anywhere reports it.
  //
  //  MEASURED: mutation M-C flips one bit of wb_ex.  C1 is the ONLY property
  //  in this file that fires, and the machine's end state is catastrophically
  //  wrong.  No other check in the project - assertion, differential or
  //  end-to-end - distinguishes that failure from correct operation.
  // ==========================================================================

  a_C1_wb_fanout_identical: assert property (@(posedge clk_i) disable iff (!rst_ni)
    wb_id === wb_ex)
    else $error("C1: Writeback's two fan-out copies differ - ID and EX disagree on the commit");

  a_C2_branch_fanout_identical: assert property (@(posedge clk_i) disable iff (!rst_ni)
    br_if === br_id)
    else $error("C2: Execute's two branch copies differ - IF and ID disagree on the flush");

  a_C3_wb_matches_mem_wb_reg: assert property (@(posedge clk_i) disable iff (!rst_ni)
    past_ok |-> (`WB_DATA(wb_id) === (w_mem_to_reg ? w_mdata : w_alu) &&
                 `WB_DEST(wb_id) === w_dest &&
                 `WB_WE(wb_id)   === w_reg_write))
    else $error("C3: the wb_update message does not match the MEM/WB register");

  // ==========================================================================
  //  D.  THE STALL TRICK, FORMALISED
  //
  //  A static contract cannot express back-pressure, and a load-use stall IS
  //  back-pressure.  The resolution is that the stall never suppresses a
  //  message; it changes the message's CONTENT.  Fetch still issues every
  //  cycle - it issues the same PC twice.  Decode still issues every cycle -
  //  it issues a bubble.  D1-D3 are the formal statement of "cadence intact,
  //  payload changed"; D4 is what makes the promise keepable at all, because
  //  an unbounded stall would be a cadence violation by another name.
  // ==========================================================================

  // D1 - the stall changes Decode's payload in the SAME cycle it is asserted.
  a_D1_stall_injects_bubble: assert property (@(posedge clk_i) disable iff (!rst_ni)
    stall |-> (`IDEX_VALID(id_ex)     === 1'b0 &&
               `IDEX_REG_WRITE(id_ex) === 1'b0 &&
               `IDEX_MEM_WRITE(id_ex) === 1'b0 &&
               `IDEX_MEM_READ(id_ex)  === 1'b0 &&
               `IDEX_BRANCH_Z(id_ex)  === 1'b0))
    else $error("D1: stall asserted but Decode did not inject a bubble");

  // D2 - and it does NOT change the cadence: Fetch still produces, it just
  //      re-issues the same PC.
  a_D2_stall_holds_pc: assert property (@(posedge clk_i) disable iff (!rst_ni)
    (stall && f_booted) |=> f_pc === $past(f_pc))
    else $error("D2: stall did not hold the PC");

  // D3 - and Decode holds the instruction rather than dropping it, which is
  //      why no skid buffer is needed anywhere in the design.
  a_D3_stall_holds_ifid: assert property (@(posedge clk_i) disable iff (!rst_ni)
    stall |=> (d_ifid_instr === $past(d_ifid_instr) &&
               d_ifid_valid === $past(d_ifid_valid)))
    else $error("D3: stall did not hold the IF/ID register");

  // D4 - the stall is self-terminating after exactly one cycle, because the
  //      bubble Decode just sent has mem_read = 0, so next cycle's shadow is
  //      clear.  An unbounded stall would be a cadence violation dressed up
  //      as a payload change, so this is a liveness obligation, not a nicety.
  a_D4_stall_self_terminates: assert property (@(posedge clk_i) disable iff (!rst_ni)
    stall |=> !stall)
    else $error("D4: stall lasted more than one cycle - cadence promise at risk");

  // D5 - the detector matches forwarding_unit.sv's spec, recomputed here from
  //      Decode's own registers.  Its inputs are registers only, which is why
  //      the wire to Fetch is short and there is no combinational loop.
  wire [5:0] d_op    = d_ifid_instr[31:26];
  wire [4:0] d_rs    = d_ifid_instr[25:21];
  wire [4:0] d_rt    = d_ifid_instr[20:16];
  wire       d_rtype = (d_op == 6'b000000);
  wire       d_lw    = (d_op == 6'b100011);
  wire       d_sw    = (d_op == 6'b101011);
  wire       d_jz    = (d_op == 6'b000010);
  wire       d_uses_rs = d_rtype | d_lw | d_sw | d_jz;
  wire       d_uses_rt = d_rtype | d_sw;
  wire       d_hz_ref  = d_sh_mem_read & (d_sh_rt != 5'd0) & d_ifid_valid &
                         ((d_uses_rs & (d_sh_rt == d_rs)) |
                          (d_uses_rt & (d_sh_rt == d_rt)));

  a_D5_hazard_detect_correct: assert property (@(posedge clk_i) disable iff (!rst_ni)
    past_ok |-> (stall === d_hz_ref))
    else $error("D5: load-use detector disagrees with the reference condition");

  // ==========================================================================
  //  E.  FLUSH - the squash must have no architectural side effect
  // ==========================================================================

  a_E1_flush_kills_decode_slot: assert property (@(posedge clk_i) disable iff (!rst_ni)
    (`BR_TAKEN(br_id) && !stall) |-> `IDEX_VALID(id_ex) === 1'b0)
    else $error("E1: a taken branch did not bubble the instruction in Decode");

  a_E2_flush_clears_ifid: assert property (@(posedge clk_i) disable iff (!rst_ni)
    (`BR_TAKEN(br_id) && !stall) |=> (d_ifid_valid === 1'b0 && d_ifid_instr === 32'd0))
    else $error("E2: a taken branch did not clear the IF/ID slot");

  // E3 - the general form, and the one that survives someone rewriting the
  //      flush mechanism: a dead slot never writes architectural state.
  a_E3_dead_slot_inert: assert property (@(posedge clk_i) disable iff (!rst_ni)
    (`IDEX_VALID(id_ex) === 1'b0) |->
      (`IDEX_REG_WRITE(id_ex) === 1'b0 &&
       `IDEX_MEM_WRITE(id_ex) === 1'b0 &&
       `IDEX_BRANCH_Z(id_ex)  === 1'b0))
    else $error("E3: an invalid slot carries an architectural side effect");

  // ==========================================================================
  //  F.  DATAPATH - forwarding, now with satisfiable antecedents
  //
  //  F1 is a reference model of Execute recomputed from Execute's own
  //  registers and the wb_ex bus.  It subsumes mux correctness, priority and
  //  the $zero gate in a single check on the ex_mem payload.  F2 and F3 are
  //  phrased independently of that model, so a regeneration that changed both
  //  the design and the transliteration in the same way would still be caught.
  // ==========================================================================

  wire        f_fw_nz = (x_fw_rd != 5'd0);
  wire        f_w_nz  = (`WB_DEST(wb_ex) != 5'd0);
  wire        f_a_ex  = x_fw_we & f_fw_nz & (x_fw_rd == x_rs);
  wire        f_a_wb  = `WB_WE(wb_ex) & f_w_nz & (`WB_DEST(wb_ex) == x_rs);
  wire [31:0] f_opA0  = f_a_wb ? `WB_DATA(wb_ex) : x_rd1;
  wire [31:0] f_opA   = f_a_ex ? x_fw_data       : f_opA0;
  wire        f_b_ex  = x_fw_we & f_fw_nz & (x_fw_rd == x_rt);
  wire        f_b_wb  = `WB_WE(wb_ex) & f_w_nz & (`WB_DEST(wb_ex) == x_rt);
  wire [31:0] f_opB0  = f_b_wb ? `WB_DATA(wb_ex) : x_rd2;
  wire [31:0] f_opB   = f_b_ex ? x_fw_data       : f_opB0;
  wire [31:0] f_alu_b = x_alu_src ? x_imm : f_opB;
  wire [31:0] f_alu_r = x_alu_sub ? (f_opA - f_alu_b) : (f_opA + f_alu_b);
  wire [ 4:0] f_dest  = x_reg_dst ? x_rd : x_rt;
  wire        f_btkn  = x_branch_zero & (f_opA == 32'd0);
  wire [31:0] f_btgt  = x_addr21 << 2;
  wire        f_ex_live = x_reg_write | x_mem_write | x_branch_zero;
  wire        f_uses_B  = ~x_alu_src | x_mem_write;

  a_F1_execute_datapath: assert property (@(posedge clk_i) disable iff (!rst_ni)
    past_ok |-> (`EXMEM_ALU(ex_mem)      === f_alu_r     &&
                 `EXMEM_WDATA(ex_mem)    === f_opB       &&
                 `EXMEM_DEST(ex_mem)     === f_dest      &&
                 `EXMEM_MEM_READ(ex_mem) === x_mem_read  &&
                 `EXMEM_MEM_WR(ex_mem)   === x_mem_write &&
                 `EXMEM_REG_WR(ex_mem)   === x_reg_write &&
                 `EXMEM_M2R(ex_mem)      === x_mem_to_reg))
    else $error("F1: ex_mem payload disagrees with the forwarding+ALU reference model");

  a_F1b_branch_resolve: assert property (@(posedge clk_i) disable iff (!rst_ni)
    past_ok |-> (`BR_TAKEN(br_if) === f_btkn && `BR_TGT(br_if) === f_btgt))
    else $error("F1b: branch resolve disagrees with the reference model");

  // F2 - $zero is never a forwarding source.  Phrased on the outcome, not on
  //      the select: when the shadow's destination is r0 and operand A reads
  //      r0, the ALU must see the architectural zero, not the shadow value.
  //      MEASURED: currently VACUOUS.  Mutation M-D (drop the guard) SURVIVES,
  //      because this program never writes a non-zero result to $zero.  Cover
  //      c_H12 below makes that visible.  Extend the stimulus; do not delete
  //      the property.
  a_F2_no_forward_from_zero: assert property (@(posedge clk_i) disable iff (!rst_ni)
    (past_ok && x_fw_we && (x_fw_rd == 5'd0) && (x_rs == 5'd0) && (x_fw_data != 32'd0)) |->
      `EXMEM_ALU(ex_mem) === (x_alu_sub ? (32'd0 - f_alu_b) : (32'd0 + f_alu_b)))
    else $error("F2: operand A was forwarded from $zero");

  // F3 - the P29 analogue, and the strongest property in this file.
  //      EX/MEM carries alu_result, which for a load is the ADDRESS; the
  //      loaded word does not exist until MEM/WB.  If the load-use interlock
  //      ever fails, Execute forwards an address where a value is expected -
  //      silently, no X, no bounds error.  This property checks the
  //      CONSEQUENCE of the interlock without referencing `stall` at all, so
  //      it survives someone deleting the hazard unit and rewriting D5 to
  //      match - which is exactly mutation M-A, where F3 is the only property
  //      in the whole file that fires.  The `f_ex_live` gate matters: forwarding into a bubble is
  //      harmless, and a bubble legitimately carries the stalled
  //      instruction's rs/rt fields.
  //      Note m_mem_to_reg and x_fw_* describe the SAME instruction: Execute
  //      latches fw_* and Memory latches em_* on the same edge.
  a_F3_no_exmem_forward_from_load: assert property (@(posedge clk_i) disable iff (!rst_ni)
    past_ok |-> !(f_ex_live && x_fw_we && (x_fw_rd != 5'd0) && m_mem_to_reg &&
                  ((x_fw_rd == x_rs) || (f_uses_B && (x_fw_rd == x_rt)))))
    else $error("F3: EX/MEM forwarded from a load in MEM - an address reached the ALU");

  // ==========================================================================
  //  G.  ARCHITECTURAL INVARIANTS
  //
  //  G1 is the property the serialised port violated for one cycle per
  //  register write (report section 5.1.1).  The 1-IPC port fixes it with the
  //  single-guarded-write idiom - a disabled write is retargeted to
  //  regs[0] := 0, which is a no-op - so there is only ever one write, and
  //  never a repair cycle.  The invariant is still not expressible in Anvil's
  //  type system, so it is still checked here.
  // ==========================================================================

  a_G1_zero_immutable: assert property (@(posedge clk_i) disable iff (!rst_ni)
    rf(5'd0) === 32'd0)
    else $error("G1: $zero is not zero");

  wire       g_do_wr = `WB_WE(wb_id) & (`WB_DEST(wb_id) != 5'd0);
  wire [4:0] g_wdest = g_do_wr ? `WB_DEST(wb_id) : 5'd0;
  wire [31:0] g_wdata = g_do_wr ? `WB_DATA(wb_id) : 32'd0;

  a_G2_commit_lands: assert property (@(posedge clk_i) disable iff (!rst_ni)
    (past_ok && g_do_wr) |=> rf($past(g_wdest)) === $past(g_wdata))
    else $error("G2: a committed write did not appear in the register file");

  a_G3_no_write_no_change: assert property (@(posedge clk_i) disable iff (!rst_ni)
    (past_ok && !g_do_wr) |=> d_regs === $past(d_regs))
    else $error("G3: the register file changed without a commit");

  a_G4_mem_read_value: assert property (@(posedge clk_i) disable iff (!rst_ni)
    past_ok |-> `MEMWB_MDATA(mem_wb) === dmem_w(m_alu[9:2]))
    else $error("G4: mem_wb.mem_data is not dmem[em_alu]");

  a_G5_store_only_when_asked: assert property (@(posedge clk_i) disable iff (!rst_ni)
    (past_ok && m_booted && !m_mem_write) |=> m_dmem === $past(m_dmem))
    else $error("G5: data memory changed without a store");

  // ==========================================================================
  //  H.  COVERS - the vacuity instrument
  //
  //  Every property above is an implication or an invariant, and an
  //  implication with an unsatisfiable antecedent passes.  In the serialised
  //  design the hazard family passed for exactly that reason.  These covers
  //  are the evidence that the antecedents fire here.  Leave them in the
  //  suite; an unhit cover is the only thing that separates "this property
  //  holds" from "this property was never tested".
  // ==========================================================================

  c_H1_stall:            cover property (@(posedge clk_i) disable iff (!rst_ni) stall);
  c_H2_flush:            cover property (@(posedge clk_i) disable iff (!rst_ni) `BR_TAKEN(br_id));
  c_H3_fwd_a_ex_mem:     cover property (@(posedge clk_i) disable iff (!rst_ni) f_a_ex);
  c_H4_fwd_a_mem_wb:     cover property (@(posedge clk_i) disable iff (!rst_ni) f_a_wb && !f_a_ex);
  // H5 and H6 are UNHIT on the current 7-instruction program - the same
  // operand-B stimulus hole the port review found in the serialised suite.
  c_H5_fwd_b_ex_mem:     cover property (@(posedge clk_i) disable iff (!rst_ni) f_b_ex);
  c_H6_fwd_b_mem_wb:     cover property (@(posedge clk_i) disable iff (!rst_ni) f_b_wb && !f_b_ex);
  c_H7_fwd_priority:     cover property (@(posedge clk_i) disable iff (!rst_ni) f_a_ex && f_a_wb);
  c_H8_wb_bypass:        cover property (@(posedge clk_i) disable iff (!rst_ni) g_do_wr);
  c_H9_mem_write:        cover property (@(posedge clk_i) disable iff (!rst_ni) m_mem_write);
  // H10 - the whole point of the exercise: five stages occupied at once.
  //       MEASURED at 27 of 40 cycles.  In the serialised design this cover
  //       is unhittable by construction, which is the one-line proof that
  //       the hazard properties there were vacuous rather than proven.
  c_H10_five_in_flight:  cover property (@(posedge clk_i) disable iff (!rst_ni)
                           f_booted && d_ifid_valid && `IDEX_VALID(id_ex) &&
                           (m_reg_write || m_mem_write) && w_reg_write);
  // H11 - a stall and a flush must both be reachable in the same run, or the
  //       D and E groups are only half tested.  (Written with a sticky flag
  //       rather than `##[1:$]`, which Verilator 5.020 does not implement.)
  logic seen_stall;
  always_ff @(posedge clk_i or negedge rst_ni)
    if (!rst_ni)   seen_stall <= 1'b0;
    else if (stall) seen_stall <= 1'b1;

  c_H11_stall_then_flush: cover property (@(posedge clk_i) disable iff (!rst_ni)
                            seen_stall && `BR_TAKEN(br_id));

  // H12 - F2's enabling condition.  UNHIT on the current program, which is why
  //       mutation M-D survives.  This cover is the difference between
  //       reporting "F2 passes" and reporting "F2 was never tested".
  c_H12_zero_fwd_candidate: cover property (@(posedge clk_i) disable iff (!rst_ni)
                              x_fw_we && (x_fw_rd == 5'd0) && (x_fw_data != 32'd0));

endmodule


// ============================================================================
//  BIND
//
//  Port expressions resolve in the scope of the TARGET (MipsPipeline), which
//  is what makes the downward hierarchical references below legal.  All 55
//  ports are connected; see the note at the top of this file about what
//  happens when they are not.
//
//  Spawn order from top.anv:
//    _spawn_0 Fetch   _spawn_1 Decode   _spawn_2 Execute
//    _spawn_3 Memory  _spawn_4 Writeback
// ============================================================================

bind MipsPipeline anvil_1ipc_sva u_sva (
  .clk_i        (clk_i),
  .rst_ni       (rst_ni),

  .if_id        (_if_id_le_req_0),
  .id_ex        (_id_ex_le_req_0),
  .ex_mem       (_ex_mem_le_req_0),
  .mem_wb       (_mem_wb_le_req_0),
  .wb_id        (_wb_id_le_req_0),
  .wb_ex        (_wb_ex_le_req_0),
  .br_if        (_br_if_le_req_0),
  .br_id        (_br_id_le_req_0),
  .stall        (_stall_le_req_0),

  .ev_fetch     (_spawn_0.EVENTS0[0].event_current),
  .ev_decode    (_spawn_1.EVENTS0[0].event_current),
  .ev_execute   (_spawn_2.EVENTS0[0].event_current),
  .ev_memory    (_spawn_3.EVENTS0[0].event_current),
  .ev_writeback (_spawn_4.EVENTS0[0].event_current),

  .f_pc         (_spawn_0.pc_q),
  .f_booted     (_spawn_0.init_done_q),

  .d_ifid_pc    (_spawn_1.ifid_pc_q),
  .d_ifid_instr (_spawn_1.ifid_instr_q),
  .d_ifid_valid (_spawn_1.ifid_valid_q),
  .d_regs       (_spawn_1.regs_q),
  .d_sh_mem_read(_spawn_1.sh_mem_read_q),
  .d_sh_rt      (_spawn_1.sh_rt_q),

  .x_rd1        (_spawn_2.ix_rd1_q),
  .x_rd2        (_spawn_2.ix_rd2_q),
  .x_imm        (_spawn_2.ix_imm_q),
  .x_addr21     (_spawn_2.ix_addr21_q),
  .x_rs         (_spawn_2.ix_rs_q),
  .x_rt         (_spawn_2.ix_rt_q),
  .x_rd         (_spawn_2.ix_rd_q),
  .x_alu_sub    (_spawn_2.ix_alu_sub_q),
  .x_alu_src    (_spawn_2.ix_alu_src_q),
  .x_reg_dst    (_spawn_2.ix_reg_dst_q),
  .x_mem_read   (_spawn_2.ix_mem_read_q),
  .x_mem_write  (_spawn_2.ix_mem_write_q),
  .x_reg_write  (_spawn_2.ix_reg_write_q),
  .x_mem_to_reg (_spawn_2.ix_mem_to_reg_q),
  .x_branch_zero(_spawn_2.ix_branch_zero_q),
  .x_fw_rd      (_spawn_2.fw_rd_q),
  .x_fw_data    (_spawn_2.fw_data_q),
  .x_fw_we      (_spawn_2.fw_we_q),

  .m_alu        (_spawn_3.em_alu_q),
  .m_wdata      (_spawn_3.em_wdata_q),
  .m_dest       (_spawn_3.em_dest_q),
  .m_mem_write  (_spawn_3.em_mw_q),
  .m_reg_write  (_spawn_3.em_rw_q),
  .m_mem_to_reg (_spawn_3.em_m2r_q),
  .m_dmem       (_spawn_3.dmem_q),
  .m_booted     (_spawn_3.init_done_q),

  .w_alu        (_spawn_4.mw_alu_q),
  .w_mdata      (_spawn_4.mw_mdata_q),
  .w_dest       (_spawn_4.mw_dest_q),
  .w_reg_write  (_spawn_4.mw_rw_q),
  .w_mem_to_reg (_spawn_4.mw_m2r_q)
);

`endif
